version: 2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          GTEST_ROOT: googletest-release-1.12.1/googletest
    steps:
      - checkout
      - run: sudo apt-get install cmake
      - run: "curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin"
      - run: "testspace config url samples.testspace.com"
      - run: "pip install gcovr"
      - run: "curl -fsSL https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz | tar -zxvf-"
      - run: |
          mkdir -p $GTEST_ROOT/build
          pushd $GTEST_ROOT/build
          cmake -DGOOGLETEST_VERSION=1.12.1 -Dgtest_build_samples=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG='-g -fprofile-arcs -ftest-coverage' ../
          make clean gtest
          popd
      - run: make -C $GTEST_ROOT/build |& tee build.log ; test ${PIPESTATUS[0]} -eq 0
      - run: $GTEST_ROOT/build/sample1_unittest --gtest_output=xml:sample1.xml
      - run: $GTEST_ROOT/build/sample2_unittest --gtest_output=xml:sample2.xml
      - run: $GTEST_ROOT/build/sample3_unittest --gtest_output=xml:sample3.xml
      - run: $GTEST_ROOT/build/sample4_unittest --gtest_output=xml:sample4.xml
      - run: $GTEST_ROOT/build/sample5_unittest --gtest_output=xml:sample5.xml
      - run: $GTEST_ROOT/build/sample6_unittest --gtest_output=xml:sample6.xml
      - run: $GTEST_ROOT/build/sample7_unittest --gtest_output=xml:sample7.xml
      - run: $GTEST_ROOT/build/sample8_unittest --gtest_output=xml:sample8.xml
      - run: $GTEST_ROOT/build/sample9_unittest --gtest_output=xml:sample9.xml
      - run: $GTEST_ROOT/build/sample10_unittest --gtest_output=xml:sample10.xml
      - run: gcovr --root ./ --filter ".*/samples/.*" --exclude ".*_unittest.*" -x -o coverage.xml
      - run:
          name: Send reports to testspace
          command: "testspace build.log{lint} [Tests]sample*.xml coverage.xml"
          when: always
